[package]
name = "ory-hydra-client"
version = "1.10.4-alpha.1"
description = "SDK Client for ORY Keto"
documentation = "https://www.ory.sh/keto/docs/sdk"
homepage = "https://www.ory.sh"
license = "Apache-2.0"
authors = ["OpenAPI Generator team and contributors"]
edition = "2018"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "^2.2"
[dependencies.reqwest]
version = "^0.10"
default-features = false
features = ["json"]

[dev-dependencies]
